import { Account, GameEvent, GameState, Settlement, DEFAULT_CONFIG, parseEvent } from './types';

export const initialState = (): GameState => ({ started: false, ended: false, accounts: {}, balances: {}, eliminated: new Set(), reversed: new Set(), events: [], invalid: false });
const copy = (s: GameState): GameState => ({ ...s, accounts: { ...s.accounts }, balances: { ...s.balances }, eliminated: new Set(s.eliminated), reversed: new Set(s.reversed), events: [...s.events], tally: s.tally?.map(x => ({ ...x })) });
const bankId = (s: GameState) => Object.values(s.accounts).find(a => a.kind === 'bank' && a.unlimited)?.id;
const activePlayers = (s: GameState) => Object.values(s.accounts).filter(a => a.kind === 'player' && !s.eliminated.has(a.id));
function validAccounts(accounts: Account[], config: typeof DEFAULT_CONFIG): boolean { const ids = new Set(accounts.map(a => a.id)); const players = accounts.filter(a => a.kind === 'player'); const banks = accounts.filter(a => a.kind === 'bank'); const pots = accounts.filter(a => a.kind === 'pot'); const colors = new Set(players.map(a => a.color)); return config.bankerMode && players.length >= 2 && players.length <= 8 && ids.size === accounts.length && colors.size === players.length && banks.length === 1 && banks[0].unlimited && pots.length <= 1 && (!config.freeParkingPot ? pots.length === 0 : pots.length === 1) && accounts.every(a => a.assets.length === 0 && (a.kind === 'bank' ? a.unlimited : !a.unlimited)); }
function change(s: GameState, id: string, delta: number): boolean { const account = s.accounts[id]; if (!account || account.unlimited) return true; const next = (s.balances[id] ?? 0) + delta; if (!Number.isSafeInteger(next)) return false; s.balances[id] = next; return true; }
function validTally(s: GameState, tally: Settlement[]): boolean { const players = Object.values(s.accounts).filter(a => a.kind === 'player'); if (tally.length !== players.length) return false; const ids = new Set(tally.map(x => x.playerId)); if (ids.size !== players.length || players.some(p => !ids.has(p.id))) return false; const active = tally.filter(x => !s.eliminated.has(x.playerId)).sort((a,b) => b.netWorth - a.netWorth); return tally.every(x => { const eliminated = s.eliminated.has(x.playerId); if (eliminated && (x.cash !== 0 || x.assetTotal !== 0 || x.netWorth !== 0 || x.rank !== undefined)) return false; if (x.cash !== (s.balances[x.playerId] ?? 0) || x.netWorth !== x.cash + x.assetTotal) return false; const total = x.mode === 'fast' ? x.valuation : (x.rows ?? []).reduce((n, r) => n + (r.kind === 'mortgage' ? -r.value : r.kind === 'property' ? r.value : r.value * (r.quantity ?? 1)), 0); if (x.assetTotal !== total || x.valuation !== total) return false; if (!eliminated) { const i = active.findIndex(y => y.playerId === x.playerId); const expected = i === 0 || active[i - 1].netWorth !== x.netWorth ? i + 1 : active[i - 1].rank; if (x.rank !== expected) return false; } return true; }); }
export function applyEvent(previous: GameState, input: GameEvent): GameState { const parsed = parseEvent(input); if (!parsed) return { ...previous, invalid: true }; if (previous.events.some(e => e.intentId === parsed.intentId)) return previous; if (parsed.seq !== previous.events.length) return { ...previous, invalid: true }; const s = copy(previous); const fail = () => ({ ...previous, invalid: true });
  switch (parsed.type) {
    case 'game.started': { const { config, accounts } = parsed.payload; if (s.started || parsed.seq !== 0 || !validAccounts(accounts, config)) return fail(); s.started = true; s.config = config; accounts.forEach(a => { s.accounts[a.id] = a; s.balances[a.id] = a.kind === 'player' ? config.startingCash : 0; }); break; }
    case 'player.joined': { const a = parsed.payload.account; if (!s.started || s.ended || s.accounts[a.id] || a.kind !== 'player' || a.unlimited || a.assets.length !== 0 || activePlayers(s).length >= 8 || Object.values(s.accounts).some(x => x.color === a.color && x.kind === 'player' && !s.eliminated.has(x.id))) return fail(); s.accounts[a.id] = a; s.balances[a.id] = s.config!.startingCash; break; }
    case 'player.renamed': { const a = s.accounts[parsed.payload.accountId]; if (!s.started || s.ended || !a || a.kind !== 'player' || Object.values(s.accounts).some(x => x.id !== a.id && x.kind === 'player' && !s.eliminated.has(x.id) && x.color === parsed.payload.color)) return fail(); s.accounts[a.id] = { ...a, name: parsed.payload.name, color: parsed.payload.color }; break; }
    case 'transfer': { const { from, to, amount } = parsed.payload; const fa = s.accounts[from], ta = s.accounts[to]; if (!s.started || s.ended || !fa || !ta || from === to || s.eliminated.has(from) || s.eliminated.has(to) || !Number.isSafeInteger(amount) || amount <= 0) return fail(); const beforeFrom = s.balances[from] ?? 0, beforeTo = s.balances[to] ?? 0; if (!change(s, from, -amount) || !change(s, to, amount)) { s.balances[from] = beforeFrom; s.balances[to] = beforeTo; return fail(); } s.events.push(parsed); if (fa.kind === 'player') s.lastPayer = from; return s; }
    case 'transfer.reversed': { const target = s.events.find(e => e.seq === parsed.payload.targetSeq); const boundary = [...s.events].reverse().find(e => e.type === 'player.eliminated')?.seq ?? -1; const latest = [...s.events].reverse().find(e => e.type === 'transfer' && e.seq > boundary && !s.reversed.has(e.seq)); if (!s.started || s.ended || !target || target.type !== 'transfer' || target.seq !== latest?.seq || s.reversed.has(target.seq)) return fail(); const beforeFrom = s.balances[target.payload.from] ?? 0, beforeTo = s.balances[target.payload.to] ?? 0; if (!change(s, target.payload.from, target.payload.amount) || !change(s, target.payload.to, -target.payload.amount)) { s.balances[target.payload.from] = beforeFrom; s.balances[target.payload.to] = beforeTo; return fail(); } s.reversed.add(target.seq); break; }
    case 'player.eliminated': { const { accountId, creditorId } = parsed.payload; const player = s.accounts[accountId], creditor = creditorId ? s.accounts[creditorId] : undefined, bank = bankId(s); if (!s.started || s.ended || !player || player.kind !== 'player' || s.eliminated.has(accountId) || (creditorId !== null && (!creditor || creditor.kind !== 'player' || creditorId === accountId || s.eliminated.has(creditorId))) || !bank) return fail(); const bal = s.balances[accountId] ?? 0; const before = { ...s.balances }; if (bal > 0 && (!change(s, accountId, -bal) || !change(s, creditorId ?? bank, bal))) { s.balances = before; return fail(); } if (bal < 0 && !change(s, accountId, -bal)) { s.balances = before; return fail(); } s.balances[accountId] = 0; s.eliminated.add(accountId); break; }
    case 'game.ended': if (!s.started || s.ended || !validTally(s, parsed.payload.tally)) return fail(); s.ended = true; s.tally = parsed.payload.tally; break;
  }
  s.events.push(parsed); return s;
}
export const fold = (events: GameEvent[]) => events.reduce(applyEvent, initialState());
